### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by StevensBenavides** [NotFenixio/notfenixio.github.io#3]
Soy DevCheck un miembro de un servidor al que fuiste staff en Discord (YouNessXz) era por una propuesta de ayudar con un proyecto.

Discord: devcheckog

O a mi GitHub.

**Comment by NotFenixio** [comment]
¿De qué trataría?

La verdad es que ya estoy metido en varios proyectos, no estoy seguro si otro más sería buena idea, pero si me comentas la idea general por encima te digo.

**Comment by StevensBenavides** [comment]
El (pico de la programación) en este caso la creación de un lenguaje de programación compilado, de tipado fuerte además memory safety, si se concreta sería otro lenguaje en el podio como Rust, Swift, Odin y Zig que actualmente son los lenguajes de sistemas del mercado más utilizados con el concepto memory safety, este lenguaje será uno de esos. Usa la caja de herramientas de Compiladores de LLVM / Clang, compila a LLVM IR y de el a varias arquitecturas como WASM, Armv8 por ejemplo. Este emite ejecutables nativos del sistema, típicamente los .exe y ejecutables de Linux por poner un ejemplo. Por ahora ya esta escrito una parte del Compilador y ya se puede hacer un Hello World desde el lenguaje. Además que también YouNessXz te quiere saludar :v.

**Comment by NotFenixio** [comment]
Uy, pues lo veo complicado, ya tengo muchas cosas que hacer en la vida real además de que últimamente he intentado estar más alejado de internet así que creo que no voy a poder. 

De todas formas, mucho ánimo y buena suerte con el proyecto 🫂

Y mándale saludos a YouNessXz de mi parte :)
